### ISSUE TITLE
Pasar Strings a Recursos

### ISSUE THREAD

**Issue by aleeherasimiuk** [UTN-FRBA-Mobile/HomeAssistant#3]
![image](https://github.com/user-attachments/assets/043a1eb9-b566-49a3-ad35-54e87b25cba7)

SI puede ser en español e ingles (también se podría hacer en francés)

**Comment by lucas-cabello** [comment]
Fixed here: https://github.com/UTN-FRBA-Mobile/HomeAssistant/pull/6
